import{a as L,S as v,i as c}from"./assets/vendor-DhWfHwn5.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const b="46051568-7c86afd7f3b7df8cfe693777e",w="https://pixabay.com/api/";let m=1;const S=async s=>{const r=`${w}?key=${b}&q=${s}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${m}`;try{return(await L.get(r)).data.hits}catch{throw new Error("Error fetching images")}},q=()=>{m+=1},$=()=>{m=1},E=new v(".gallery a",{captionDelay:250,captionsData:"alt"}),P=s=>{const r=document.querySelector(".gallery");if(r.innerHTML="",s.length===0){c.error({message:"Sorry, no images found."});return}const a=s.map(({webformatURL:l,largeImageURL:e,tags:t,likes:n,views:h,comments:f,downloads:p})=>`<div class="gallery-item">
            <a href="${e}" class="gallery-link">
                <img src="${l}" alt="${t}" />
            </a>
            <div class="image-info">
                <span>Likes: ${n}</span>
                <span>Views: ${h}</span>
                <span>Comments: ${f}</span>
                <span>Downloads: ${p}</span>
            </div>
        </div>`).join("");r.innerHTML=a,E.refresh()},u=document.querySelector(".search-form"),o=document.createElement("button");o.textContent="Load more";o.classList.add("load-more","hidden");document.body.appendChild(o);const g=document.querySelector(".loader");let d="",i=[];u.addEventListener("submit",async s=>{if(s.preventDefault(),d=u.elements.query.value.trim(),!d){c.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}$(),o.classList.add("hidden"),i=[],await y()});o.addEventListener("click",async()=>{q(),await y()});const y=async()=>{var s;try{g.classList.remove("hidden");const r=await S(d);if(i.length===0&&(document.querySelector(".gallery").innerHTML=""),r.length===0){c.error({message:"Sorry, there are no images matching your search query. Please try again!"}),o.classList.add("hidden");return}i=[...i,...r],P(i),r.length<15?(o.classList.add("hidden"),c.info({message:"We're sorry, but you've reached the end of search results."})):o.classList.remove("hidden");const a=((s=document.querySelector(".gallery-item"))==null?void 0:s.getBoundingClientRect().height)||0;window.scrollBy({top:a*2,behavior:"smooth"})}catch(r){console.error(r),c.error({message:"Error fetching images."})}finally{g.classList.add("hidden")}};o.style.marginBottom="32px";
//# sourceMappingURL=index.js.map
