import{a as L,S as v,i as c}from"./assets/vendor-DhWfHwn5.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const b="46051568-7c86afd7f3b7df8cfe693777e",w="https://pixabay.com/api/";let m=1;const $=async s=>{const t=`${w}?key=${b}&q=${s}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${m}`;try{return(await L.get(t)).data.hits}catch{throw new Error("Error fetching images")}},S=()=>{m+=1},E=()=>{m=1},q=new v(".gallery a",{captionDelay:250,captionsData:"alt"}),P=s=>{const t=document.querySelector(".gallery");if(t.innerHTML="",s.length===0){c.error({message:"Sorry, no images found."});return}const n=s.map(({webformatURL:i,largeImageURL:e,tags:r,likes:a,views:p,comments:h,downloads:y})=>`<div class="gallery-item">
            <a href="${e}" class="gallery-link">
                <img src="${i}" alt="${r}" />
            </a>
            <div class="image-info">
                <span>Likes: ${a}</span>
                <span>Views: ${p}</span>
                <span>Comments: ${h}</span>
                <span>Downloads: ${y}</span>
            </div>
        </div>`).join("");t.innerHTML=n,q.refresh()},u=document.querySelector(".search-form"),o=document.createElement("button");o.textContent="Load more";o.classList.add("load-more","hidden");document.body.appendChild(o);const f=document.querySelector(".loader");let d="",l=[];u.addEventListener("submit",async s=>{s.preventDefault(),d=u.elements.query.value.trim(),d&&(E(),o.classList.add("hidden"),l=[],await g())});o.addEventListener("click",async()=>{S(),await g()});const g=async()=>{var s;try{f.classList.remove("hidden");const t=await $(d);if(t.length===0){c.error({message:"Sorry, no images found."}),o.classList.add("hidden");return}l=[...l,...t],P(l),t.length<15?(o.classList.add("hidden"),c.info({message:"We're sorry, but you've reached the end of search results."})):o.classList.remove("hidden");const n=((s=document.querySelector(".gallery-item"))==null?void 0:s.getBoundingClientRect().height)||0;window.scrollBy({top:n*2,behavior:"smooth"})}catch(t){console.error(t),c.error({message:"Error fetching images."})}finally{f.classList.add("hidden")}};o.style.marginBottom="32px";
//# sourceMappingURL=index.js.map
